# Generated by Django 2.2.6 on 2019-10-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
