# Generated by Django 2.2.6 on 2019-10-29 02:22

from django.db import migrations

def fill_department(apps, schema_editor):
    depts = apps.get_model('users','UserProfile')
    for dep in depts.objects.all():
        dep.department = 'General'
        dep.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_department'),
    ]

    operations = [ 
        migrations.RunPython(fill_department),
    ]
