# Generated by Django 2.2.5 on 2019-11-25 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191122_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='from_date',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='to_date',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
    ]
