# Generated by Django 2.2.6 on 2019-11-26 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191125_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='from_date',
            field=models.DateField(default=datetime.date(2019, 11, 26)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='to_date',
            field=models.DateField(default=datetime.date(2019, 11, 26)),
        ),
    ]
