# Generated by Django 2.2.6 on 2019-11-26 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191126_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='from_date',
            field=models.DateField(default=datetime.date(2019, 11, 26), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='to_date',
            field=models.DateField(default=datetime.date(2019, 11, 26), null=True),
        ),
    ]
