# Generated by Django 2.2.5 on 2019-11-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191126_0605'),
        ('users', '0007_auto_20191126_0348'),
    ]

    operations = [
    ]
