# Generated by Django 2.2.5 on 2019-11-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_fname', models.CharField(max_length=30)),
                ('faculty_lname', models.CharField(max_length=30)),
                ('facult_department', models.CharField(max_length=20)),
                ('faculty_email', models.EmailField(blank=True, max_length=70)),
                ('faculty_phoneno', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default1.jpg', upload_to='faculty_profile_picture')),
            ],
        ),
    ]
