# Generated by Django 2.2.5 on 2019-11-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='facult_department',
            new_name='faculty_department',
        ),
    ]
