# Generated by Django 2.2.6 on 2019-11-05 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('publisher', models.CharField(max_length=30)),
                ('num_pages', models.IntegerField()),
                ('isbn_number', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default_book.jpg', upload_to='books_pictures')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
