# Generated by Django 2.2.6 on 2019-11-06 22:35

from django.db import migrations
from django.utils.text import slugify


def adding_slug_title(apps, schema_editor):
    Books = apps.get_model('books','Book')
    for book in Books.objects.all():
        book.slug = slugify(book.book_name)
        book.save()

class Migration(migrations.Migration):
  
    dependencies = [
        ('books', '0002_auto_20191106_2213'),
    ]

    operations = [
        migrations.RunPython(adding_slug_title),
    ]
