# Generated by Django 2.2.6 on 2019-11-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191106_2235'),
        ('books', '0003_auto_20191106_2230'),
    ]

    operations = [
    ]
