# Generated by Django 2.2.6 on 2019-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191106_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
