# Generated by Django 2.2.6 on 2019-11-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20191108_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=30), max_length=30, unique=True),
        ),
    ]
