# Generated by Django 2.2.6 on 2019-11-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20191109_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
