# Generated by Django 2.2.6 on 2019-11-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20191109_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=80, null=True),
        ),
    ]
