# Generated by Django 2.2.6 on 2019-11-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20191109_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=80, null=True),
        ),
    ]
