# Generated by Django 2.2.6 on 2019-11-10 02:42

from django.db import migrations

def populate_book_description(apps,schema_editor):
    books = apps.get_model('books','Book')
    for book in books.objects.all():
        book.book_description ="Description of the book goes here"
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_book_description'),
    ]

    operations = [
        migrations.RunPython(populate_book_description),
    ]
