# Generated by Django 2.2.6 on 2019-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20191110_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='This field will get filled automatically. Pleaese leave it blank', max_length=80, null=True),
        ),
    ]
