# Generated by Django 2.2.6 on 2019-11-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20191111_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_in_library',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_store',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='library_shelf',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
