# Generated by Django 2.2.6 on 2019-11-11 01:38

from django.db import migrations

def fill_libray_store_fields(apps, schema_editor):
    books = apps.get_model('books','Book')
    for book in books.objects.all():
        book.available_in_library=True
        book.library_shelf = 'A23'
        book.book_store = 'http://localhost'
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20191111_0130'),
    ]

    operations = [
        migrations.RunPython(fill_libray_store_fields),
    ]
