# Generated by Django 2.2.6 on 2019-11-22 00:44

from django.db import migrations


def auto_fill_user_id(apps,schema):
    order_items = apps.get_model('orders','OrderItem')
    users = apps.get_model('auth','User')
    inst, _ = users.objects.get_or_create(is_superuser='t',\
                                is_staff='t')
    for items in order_items.objects.all():
        items.user = inst
        items.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_user'),
    ]

    operations = [
        migrations.RunPython(auto_fill_user_id),
    ]
