# Generated by Django 2.2.6 on 2019-11-25 04:44

from django.db import migrations

def update_total_price(apps,schema):
    Orders = apps.get_model('orders','Orders')
    ords_item = apps.get_model('orders','OrderItem')
    for row in Orders.objects.all():
        otms = ords_item.objects.filter(order_id=row.id)
        total = 0
        for j in otms:
            total += (j.quantity * j.price)
        row.total_price = total
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_total_price'),
    ]

    operations = [
        migrations.RunPython(update_total_price),
    ]